- pyicloud/base.py
- pyicloud/services/__init__.py
- pyicloud/services/hidemyemail.py
- tests/const_login.py
> add hidemyemail service to icloud wrapper

- pyicloud/base.py
> Move endpoints of Chinese iCloud account to icloud.com.cn

- pyicloud/services/photos.py
https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcfromtimestamp
```python
```
> Avoid `datetime.utcfromtimestamp` Python 3.12 deprecation warning

- pyicloud/services/drive.py
> fix: wrap object name with basename for path fix without root

- pyicloud/services/calendar.py
Fixes #330 with @zarkin404's work.
```python
```
> fix: Update calendar.py dsid param

- pyicloud/services/photos.py
> Shared album picklepete

- pyicloud/services/drive.py
> Fix for drive operations requiring clientId

- pyicloud/services/drive.py
> Fix for iCloud Drive objects throwing str/type/repr errors, fix for #464

- README.md
> README updates from @kavaacs

- README.rst
- pyicloud/services/drive.py
- tests/__init__.py
- tests/const_drive.py
- tests/test_drive.py
> Support iCloud Drive "Trash" operations (enter "Trash", "Restore" files, and "Delete forever" files from Trash.) - picklepete/pyicloud#467

- README.rst
- pyicloud/base.py
- pyicloud/services/photos.py
- pyicloud/services/ubiquity.py
> Fix 192 upload photos

- pyicloud/services/photos.py
- setup.py
> revving pycloud version, allowing random access to photos

- README.rst
- pyicloud/base.py
- pyicloud/services/calendar.py
> Calendar Service Overhaul

- .vscode/launch.json
- README.md
- examples.py
- pyicloud/exceptions.py
- pyicloud/services/contacts.py
- pyicloud/services/drive.py
- pyicloud/services/findmyiphone.py
- pyicloud/services/photos.py
- pyicloud/services/ubiquity.py
- pyicloud/session.py
- tests/conftest.py
- tests/test_drive.py
```python
```
- This PR fixes or closes issue: fixes N/A
- This PR is related to issue: N/A
> Added end to end examples and fixed services

- .github/workflows/publish.yml
- MANIFEST.in
- pyproject.toml
```python
```
- This PR fixes or closes issue: fixes  N/A
- This PR is related to issue: N/A
> Removed legacy files and updated publishing

- .github/ISSUE_TEMPLATE/config.yml
> Cleanup-issue-templates

- pyicloud/services/photos.py
> refactor photos do reduce complexity and duplication

- pyicloud/services/account.py
- tests/test_account.py
> updated skipped test to work on all python versions

- pyicloud/base.py
- pyicloud/session.py
- tests/conftest.py
- tests/test_base.py
> Session-update

- examples.py
- pyicloud/base.py
- pyicloud/services/calendar.py
- pyicloud/services/contacts.py
- pyicloud/services/findmyiphone.py
- pyicloud/services/hidemyemail.py
- pyicloud/services/photos.py
- pyicloud/services/ubiquity.py
- pyicloud/session.py
- tests/conftest.py
- tests/test_photos.py
> Photo folder handling

- README.md
- pyicloud/services/hidemyemail.py
- tests/conftest.py
- tests/test_hidemyemail.py
```python
```
- This PR fixes or closes issue: fixes #54
- This PR is related to issue: #54 
> Added HME enpoints found by @MrJarnould

- pyicloud/services/calendar.py
- pyicloud/services/reminders.py
- tests/test_calendar.py
- tests/test_reminders.py
- tests/test_ubiquity.py
> Add-additional-tests

- .github/dependabot.yml
- .github/workflows/sonarcube.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- examples.py
- pyicloud/services/calendar.py
- requirements.txt
- tests/test_calendar.py
> Workflow-fixes

- pyicloud/base.py
- pyicloud/services/findmyiphone.py
- tests/conftest.py
- tests/test_drive.py
- tests/test_findmyiphone.py
> Improve-test-coverage

- pyicloud/base.py
- tests/__init__.py
The requests method can take care of the JSON serialization, there's no need to manually `json.dumps()`
```python
```
> simplify json requests

- .github/workflows/tests.yml
- README.md
- examples.py
- pyicloud/base.py
- pyproject.toml
- requirements.txt
- requirements_all.txt
- sonar-project.properties
- tests/test_base.py
Currently the code only works with accounts which are secured with device- or SMS-based 2FA. It doesn't work with accounts which are secured by FIDO2 hardware security keys. This PR adds support for the latter.
- This PR fixes or closes issue: fixes #83 
> feature: support FIDO2 security keys

- pyproject.toml
Fix release issues
- This PR fixes or closes issue: fixes #90 
> fix: specify content-type for README in setuptools dynamic configuration

- pyicloud/services/drive.py
- tests/test_drive.py
simplify drive.py JSON handling
```python
```
> simplify drive.py JSON handling

- pyicloud/base.py
- tests/conftest.py
- tests/test_base.py
Closes #84.
The implementation was adapted from
https://github.com/foxt/icloud.js/blob/de2d21907370443ddfba87420e2812f8559213ed/src/index.ts#L400-L458
For details see https://github.com/foxt/icloud.js/issues/4
I'm not sure if this is the most fitting way to implement it, so I wanted to get some feedback and a green light on that before writing any tests. 
```python
```
> feature: ADP support

- examples.py
None
I needed to debug an open issue #106 and needed to use an SSL proxy to view the transactions with icloud.
However, CODE_SAMPLES.md, which has this support, hasn't been updated in 5 years and that code didn't work, so I updated 
examples.py with changes that are non-breaking and optional. 
Along the way, I improved the command-line support to flag an error if either username or password is missing.
And added the ability to control the logging level, another feature of the outdated CODE_SAMPLES.md.
`python example.py --username "apple_username" --password "apple_password"`
- should work without issue for normal system operation
- should fail if SSL proxy is used (such as Charles Proxy)
`python example.py --username "apple_username" --password "apple_password" --disable-ssl-verify`
- …
> Examples.py: Added support for disabling SSL verification, adjusting logging level, and improved command-line support

- README.md
> Update Discord Link

- README.md
- examples.py
- pyicloud/services/calendar.py
- pyicloud/utils.py
- tests/test_calendar.py
This PR fixes critical bugs in the calendar service that prevented event creation and adds comprehensive new features for invitee management and alarms. The primary focus is resolving the "ctag not found" error reported in issue #82, which was caused by incorrect GUID usage in the add_event and remove_event methods.
Key improvements include:
- Fixed GUID confusion bug where event GUID was used instead of calendar GUID for ctag lookup
- Corrected API payload structure to use proper camelCase field names expected by Apple's API
- Added comprehensive invitee management functionality
- Implemented full alarm support for calendar events
- Enhanced data validation and error handling
- Eliminated dangerous mutable default values
- Added extensive test coverage for all new functionality
```python …
```
> Fix critical calendar service bugs and add comprehensive features

- pyicloud/services/photos.py
Support live photos
```python
if p.is_live_photo:
with open(p.versions["original_video"]['filename'], 'wb') as f:
f.write(p.download("original_video").raw.read())
```
- This PR fixes or closes issue: fixes #119 
> Support live photos

- README.md
- pyicloud/base.py
- pyicloud/cmdline.py
- pyicloud/exceptions.py
- tests/test_base.py
Added support to accept iCloud terms and conditions
> Support the handling new iCloud terms and conditions
